# Generated by Django 2.2.6 on 2021-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Assessee')),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_type', models.CharField(choices=[('F', 'Farmer'), ('S', 'SaAEO')], default='F', max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('twelve_digit_TIN', models.CharField(default='00', max_length=15)),
                ('old_TIN', models.CharField(default='00', max_length=16)),
            ],
        ),
    ]
