language: python # => 1
    services: # => 3
      - mysql
    env: # => 4
      -DJANGO=2.2.6 DB=mysql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - mysql -e 'create database taxbd;' -u root
    script: # => 7
      - python manage.py test